2024-12-05 08:47:18,038 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:50:29,638 - src.server - ERROR - [server.py:42] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'callback'
2024-12-05 08:50:29,826 - src.server - ERROR - [server.py:42] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'callback'
2024-12-05 08:50:29,875 - src.server - ERROR - [server.py:42] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'callback'
2024-12-05 08:50:44,976 - src.server - ERROR - [server.py:42] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'callback'
2024-12-05 08:51:16,972 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:51:21,156 - src.server - ERROR - [server.py:43] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'channel'
2024-12-05 08:51:21,202 - src.server - ERROR - [server.py:43] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'channel'
2024-12-05 08:51:26,966 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:51:27,028 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:51:31,015 - src.server - ERROR - [server.py:43] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'channel'
2024-12-05 08:51:31,037 - src.server - ERROR - [server.py:43] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'channel'
2024-12-05 08:51:43,598 - src.server - ERROR - [server.py:43] - Error subscribing to message bus: MessageBus.subscribe() missing 1 required positional argument: 'channel'
2024-12-05 08:53:17,627 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:53:17,707 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:54:39,985 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:54:39,986 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 08:54:39,986 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 09:00:06,283 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 09:00:06,313 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
2024-12-05 09:00:06,331 - root - ERROR - [logging_config.py:83] - Uncaught exception:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 334, in _bootstrap
    util._flush_std_streams()
  File "C:\Users\Ross Brown\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\util.py", line 435, in _flush_std_streams
    sys.stdout.flush()
OSError: [Errno 22] Invalid argument
